### ISSUE TITLE
Plugin addition

### ISSUE THREAD

**Issue by Denisalik** [wunderschild/wsgraph#2]
We have method `plugin` in class `GraphBuilder`, it would be easier to have method that add all plugins. Can you add this method(or change signature argument `plugin: PluginIn` to `plugin: PluginIn | PluginIn[]`).

**Comment by Denisalik** [comment]
or even `plugin: PluginIn | PluginIn[] | () => PluginIn`

**Comment by thedeadferryman** [comment]
This will not be possible to do without breaking proper type configuration. As for now, plugins may apply type restrictions on `NodeType`, `EdgeType` and `PluginContext`. This would not be possible with arrays due to TS specifics.
